#!/bin/sh

# Usage: git-create-branch <branch_name>
 
if [ $# -ne 1 ]; then
    echo "Usage: $0 <branch_name>" >&2
    exit 127
fi
 
branch_name="$1"
git push origin origin:refs/heads/${branch_name}
git fetch origin
git checkout --track -b ${branch_name} origin/${branch_name}
git pull

