#*****************************************************************************
# RHQ Agent Java Service Wrapper Settings Include File
#
# This file specifies a set of additional environment variables that will be
# applied to the RHQ Agent JVM.  This file will likely be empty.
#
# If adding additional Java properties note that the properties must follow
# a strict number ordering (that continues from rhq-agent-wrapper.conf)
# and currently must start with:
#
# wrapper.java.additional.9=
#
# For example, to set a non-default temp directory for Java:
#   Note: use forward slashes for directories:
#
# wrapper.java.additional.9="-Djava.io.tmpdir=c:/temp"
#
#*****************************************************************************

